### ISSUE TITLE
Dimension and Shape for LLUL

### ISSUE THREAD

**Issue by enzyme69** [hnmr293/sd-webui-llul#10]
My image is in ratio 3:2 or 2:3, I can't seem to get the LLUL to work properly, as it is complaining:

```
100%|█████████████████████████████████████████████████████████████████████████████| 16/16 [00:26<00:00,  1.67s/it]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x3be1e31f0>]: RuntimeError
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 151, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 113, in load_lora
    module.weight.copy_(weight)
RuntimeError: output with shape [96, 320] doesn't match the broadcast shape [96, 320, 96, 320]
```

**Comment by hnmr293** [comment]
I could not reproduce the error.
Please let me know your generation information such as PNG info.

This is the image I've generated. The size is 768x512, in ratio 3:2. See PNG info for generation details.
![1997573138-2804125183](https://user-images.githubusercontent.com/120772120/223707260-6bff26a1-ab01-4df6-8fe0-2d69a58812be.png)

**Comment by fractal-fumbler** [comment]
It's problem with Lora not with extension.

are you trying to use LoRA (downloaded or trained) with SD-2.x checkpoint?

upd: this error started to appear after installation of extension?
