### ISSUE TITLE
unexpected keyword argument 'force_float' on latest update

### ISSUE THREAD

**Issue by matrix4767** [hnmr293/sd-webui-llul#11]
Error running process: G:\stable-webui\extensions\sd-webui-llul\scripts\llul.py
Traceback (most recent call last):
  File "G:\stable-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "G:\stable-webui\extensions\sd-webui-llul\scripts\llul.py", line 146, in process
    self.last_hooker = Hooker(
TypeError: Hooker.__init__() got an unexpected keyword argument 'force_float'

**Comment by hnmr293** [comment]
Thank you for your feedback.
Please update this extension and try it again.
