### ISSUE TITLE
llul not loading

### ISSUE THREAD

**Issue by dnihil** [hnmr293/sd-webui-llul#17]
llul wasn't showing up and I don't understand any of these words to troubleshoot for myself.

`Error loading script: llul.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py", line 194, in <module>
    init_xyz(Script)
  File "E:\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul_xyz.py", line 61, in init_xyz
    define('Enabled', 0, to_bool, choices=['false', 'true'])
  File "E:\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul_xyz.py", line 59, in define
    data.module.axis_options.append(AxisOption(f'LLuL {param}', type, fn, choices=lambda: choices))
TypeError: AxisOption.__new__() got an unexpected keyword argument 'choices'`

**Comment by hnmr293** [comment]
Thank you for your feedback.
It seems to be conflicting with some other extensions.
I have fixed it. Please update and try it again.

**Comment by dnihil** [comment]
It is working now! 
Thanks a bunch, thought it was something I was doing wrong.
