### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by chdlc** [hnmr293/sd-webui-llul#38]
I am getting these errors in latest SD WebUI

```
*** Error running postprocess: D:\Programas\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py,  1.14it/s]
    Traceback (most recent call last):
      File "D:\Programas\stable-diffusion-webui\modules\scripts.py", line 750, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\Programas\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py", line 236, in postprocess
        xi0 = int(x)
    ValueError: invalid literal for int() with base 10: '133.1999969482422'
```

ValueError value changes when the gray box is moved to other place in the canvas. Tried a few things, like disabling Hypertile, AgentAttention, changing resolutions, etc. but nothing worked.

**Comment by hnmr293** [comment]
Thank you for your feedback.
I have updated for this issue.
Please try it again, and reopen issue if it is not fixed.

**Comment by chdlc** [comment]
> Thank you for your feedback. I have updated for this issue. Please try it again, and reopen issue if it is not fixed.

Thanks! It works now, but I was doing at 372px width and had to down the value to 368px to make it work. This was the error in case it's useful:
```
Error running postprocess: D:\Programas\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py,  1.14it/s]
    Traceback (most recent call last):
      File "D:\Programas\stable-diffusion-webui\modules\scripts.py", line 750, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\Programas\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py", line 263, in postprocess
        area_tensor.mul_(area)
    RuntimeError: The size of tensor a (368) must match the size of tensor b (372) at non-singleton dimension 2
```
